[project]
name = "runtime-failure-detection"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "h5py>=3.15.1",
    "huggingface-hub>=1.3.1",
    "lerobot>=0.3.3",
    "numpy>=2.4.1",
    "opencv-python-headless>=4.11.0.86",
    "tyro>=1.0.4",
]
