defaults:
  - base_config
  - task: base_task
  - _self_

# OpenPI policy configuration
policy_config: pi0_ur5_merged
checkpoint_dir: ../openpi-failure-detection/checkpoints/pi0_ur5_merged/merged-training/29999

# Set the size to which camera images are resized before being passed to the policy
resize_size: 896
replan_steps: 16
horizon: 700

# Cameras
camera_names:
  - agentview
  - robot0_eye_in_hand
cam_w: 896
cam_h: 896

# Output video
save_video: true

# Number of trials to run per task
num_trials_per_task: 50

seed: 3
logging: INFO

hydra:
  job:
    chdir: false
  run:
    dir: .
  sweep:
    dir: ./multirun
    subdir: ${now:%Y-%m-%d_%H-%M-%S}
