# Template configuration for converting LeRobot HDF5 datasets
# Repository configuration
repo-id: "lerobot/ur5e-square-nut-pick-place-v1"
push_to_hub: true
private_repo: false
tags:
  - "LeRobot"
  - "robotics"
  - "ur5e"
  - "manipulation"

# Dataset conversion configuration
input_path: "data/lerobot/raw"
output_dir: "data/lerobot/converted"

# Configuration for converting LeRobot HDF5 datasets
fps: 20
robot_type: "ur5e"
task: "Do something" # Default task name if task_mapping is not provided
task_mapping:
  "square_d1_ur5e.hdf5": "Pick a square nut and place on a peg"
  "threading_d1_ur5e.hdf5": "Pick a needle and thread through a hole on a tripod."

# Batch processing configuration
batch_size: 1 # Default batch size for processing frames. Should 