# Repository configuration
repo_id: "ravtscheev/ur5e-hammer-cleanup-task"
push_to_hub: false
private_repo: false
tags:
  - "LeRobot"
  - "robotics"
  - "ur5e"
  - "manipulation"

# Dataset conversion configuration
input_path: "./data/mimicgen/hammer_cleanup_UR5e/hammer_cleanup_task_D1_UR5e/demo.hdf5"
output_dir: "./data/lerobot/"

# Configuration for converting LeRobot HDF5 datasets
fps: 20
robot_type: "ur5e"
task: "Do something" # Default task name if task_mapping is not provided
task_mapping:
  "demo.hdf5": "Open the drawer, pick up the hammer, place the hammer into the drawer, and close the drawer."

batch_size: 4 # Default batch size for processing frames.