# Repository configuration
repo_id: "ravtscheev/ur5e-kitchen-task"
push_to_hub: false
private_repo: false
tags:
  - "LeRobot"
  - "robotics"
  - "ur5e"
  - "manipulation"

# Dataset conversion configuration
input_path: "./data/mimicgen/kitchen_UR5e/kitchen_task_D1_UR5e/demo.hdf5"
output_dir: "./data/lerobot/"

# Configuration for converting LeRobot HDF5 datasets
fps: 20
robot_type: "ur5e"
task: "Do something" # Default task name if task_mapping is not provided
task_mapping:
  "demo.hdf5": "Turn on the stove, place the pot on the stove, put the bread into the pot, move the pot to the serving region, and turn off the stove."

batch_size: 4 # Default batch size for processing frames.