# Repository configuration
repo_id: "ravtscheev/ur5e-three-piece-assembly"
push_to_hub: false
private_repo: false
tags:
  - "LeRobot"
  - "robotics"
  - "ur5e"
  - "manipulation"

# Dataset conversion configuration
input_path: "./data/mimicgen_generated/three_piece_assembly_UR5e/three_piece_assembly_task_D1_UR5e/demo.hdf5"
output_dir: "./data/lerobot/"

# Configuration for converting LeRobot HDF5 datasets
fps: 20
robot_type: "ur5e"
task: "Do something" # Default task name if task_mapping is not provided
task_mapping:
  "demo.hdf5": "Assemble the structure by inserting the first piece into the base, then inserting the second piece into the first piece."

batch_size: 4 # Default batch size for processing frames.